name: Deployment (Container)
on:
  push:
    branches:
      - main
      - dev
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    # container:
    #   image: node:16
    #   # Add environment variables yhat the image itself needs
    #   # env:
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb # mongodb+srv
      # Since the job is now running outside container, needs IP and port (not just 'mongodb')
      MONGODB_CLUSTER_ADDRESS: 127.0.0.1:27017 # cluster0.ntrwp.mongodb.net
      MONGODB_USERNAME: root # ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: example # ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    services:
      mongodb:
        image: mongo
        # Since the job is now running outside container, ports needs to be forwarded
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
      # some-other-service
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
